import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "BlueChannel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-gradient-to-b from-black to-backgroundborder border-b-amber-900 ">
        {children}
      </body>
    </html>
  );
}
