import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "BlueChannel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-gradient-to-b from-black to-background border border-b-amber-900 mx-auto px-5 py-8 md:py-0 ">
        {children}
      </body>
    </html >
  );
}
