import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Fragância divina",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          as="image"
          href="/logodosite.png"
          fetchPriority="high"
        />
        <link rel="icon" href="/logodosite.png" type="image/png" />
      </head>
      <body className="
       bg-background ">
        {children}
      </body>
    </html>
  );
}
