import type { Metadata } from "next";
import { ReactNode } from 'react';
import './globals.css'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  );
}
